#!/usr/bin/env python3
"""
Twiddle Factor Generator for NWC NTT

Generates twiddle factors using psi (primitive 2N-th root) for NTT.
Outputs:
  - Hex file for BRAM initialization ($readmemh)
  - SystemVerilog ROM (optional, for reference/comparison)

Parameters (default for Dilithium):
  N = 256 (or 4096 for larger NTT)
  Q = 8380417
  psi = 1239911 (primitive 512-th root: psi^512 = 1, psi^256 = -1)

Usage:
  python generate_twiddles.py [--n N] [--output-dir DIR]
"""

import argparse
from pathlib import Path


# Default NTT Parameters (Dilithium)
DEFAULT_N = 256
DEFAULT_Q = 8380417
DEFAULT_PSI = 1239911


def compute_twiddles(n, q, psi):
    """
    Compute all twiddle factors: psi^k mod q for k = 0, 1, ..., n-1

    Args:
        n: NTT size
        q: Modulus (prime)
        psi: Primitive 2N-th root of unity mod q

    Returns:
        List of n twiddle factors
    """
    return [pow(psi, k, q) for k in range(n)]


def verify_psi_properties(psi, n, q):
    """Verify psi is a valid primitive 2N-th root of unity"""
    psi_2n = pow(psi, 2 * n, q)
    psi_n = pow(psi, n, q)

    print(f"Verifying psi properties:")
    assert psi_2n == 1, f"  psi^{2 * n} = {psi_2n} != 1"
    print(f"  psi^{2 * n} = 1 (mod {q})")

    assert psi_n == q - 1, f"  psi^{n} = {psi_n} != -1"
    print(f"  psi^{n} = -1 (mod {q})")

    print(f"  Valid primitive {2 * n}-th root of unity")


def generate_hex_file(twiddles, output_file, width=32):
    """
    Generate hex file for $readmemh initialization

    Format: One hex value per line, no address, MSB first
    Example:
        00000001
        0012F2A7
        ...
    """
    hex_width = (width + 3) // 4  # Number of hex digits

    with open(output_file, "w") as f:
        for tw in twiddles:
            f.write(f"{tw:0{hex_width}X}\n")

    print(f"Generated hex file: {output_file}")
    print(f"  Entries: {len(twiddles)}")
    print(f"  Width: {width} bits ({hex_width} hex digits)")


def generate_systemverilog_rom(twiddles, output_file, n, q, psi, width=32):
    """Generate SystemVerilog ROM module with case statement (for reference)"""
    addr_width = (len(twiddles) - 1).bit_length()
    if addr_width == 0:
        addr_width = 1

    sv_code = f"""\
`timescale 1ns / 1ps

//==============================================================================
// psi-Based Twiddle Factor ROM for NWC NTT
//==============================================================================
// Contains precomputed twiddle factors using psi indexed by address
//
// Parameters:
//   - N = {n} (NTT size)
//   - Q = {q} (modulus)
//   - psi = {psi} (primitive {2 * n}-th root of unity)
//
// Stores psi^addr for addr in [0, N-1]
// Total entries: {len(twiddles)}
//
// Auto-generated by scripts/generate_twiddles.py
//==============================================================================

module twiddle_rom #(
    parameter int N = {n},
    parameter int WIDTH = {width},
    parameter int ADDR_WIDTH = {addr_width}
) (
    input  logic [ADDR_WIDTH-1:0] addr,
    output logic [WIDTH-1:0]      twiddle
);

    // Twiddle factor lookup table
    always_comb begin
        case (addr)
"""

    for i, tw in enumerate(twiddles):
        sv_code += f"            {addr_width}'d{i}: twiddle = {width}'d{tw};\n"

    sv_code += f"""\
            default: twiddle = {width}'d0;
        endcase
    end

endmodule
"""

    with open(output_file, "w") as f:
        f.write(sv_code)

    print(f"Generated SystemVerilog ROM: {output_file}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate NTT twiddle factors for hardware implementation"
    )
    parser.add_argument(
        "--n", type=int, default=DEFAULT_N, help=f"NTT size (default: {DEFAULT_N})"
    )
    parser.add_argument(
        "--q", type=int, default=DEFAULT_Q, help=f"Modulus (default: {DEFAULT_Q})"
    )
    parser.add_argument(
        "--psi",
        type=int,
        default=DEFAULT_PSI,
        help=f"Primitive root (default: {DEFAULT_PSI})",
    )
    parser.add_argument("--width", type=int, default=32, help="Bit width (default: 32)")
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Output directory (default: ../rtl)",
    )
    parser.add_argument(
        "--no-rom", action="store_true", help="Skip generating SystemVerilog ROM"
    )
    args = parser.parse_args()

    # Determine output directory
    script_dir = Path(__file__).parent
    if args.output_dir:
        output_dir = Path(args.output_dir)
    else:
        output_dir = script_dir.parent / "rtl"
    output_dir.mkdir(exist_ok=True)

    print("=" * 70)
    print(" NTT Twiddle Factor Generator (Forward)")
    print("=" * 70)
    print(f"Parameters: N={args.n}, Q={args.q}, psi={args.psi}")
    print()

    # Verify psi properties
    verify_psi_properties(args.psi, args.n, args.q)
    print()

    # Compute twiddles
    print(f"Computing {args.n} twiddle factors...")
    twiddles = compute_twiddles(args.n, args.q, args.psi)
    print(f"  First 5: {twiddles[:5]}")
    print(f"  Last 5:  {twiddles[-5:]}")
    print()

    # Generate hex file for BRAM
    hex_file = output_dir / "twiddle_forward.hex"
    generate_hex_file(twiddles, hex_file, args.width)

    # Generate SystemVerilog ROM (optional)
    if not args.no_rom:
        rom_file = output_dir / "twiddle_rom.sv"
        generate_systemverilog_rom(
            twiddles, rom_file, args.n, args.q, args.psi, args.width
        )

    print()
    print("=" * 70)
    print(" Generation Complete!")
    print("=" * 70)


if __name__ == "__main__":
    main()
