#!/usr/bin/env python3
"""
ψ-Based Twiddle Factor Generator for NWC NTT

Generates twiddle factors using ψ (primitive 2N-th root) with bit-reversed indexing
For N=256 point NTT over Z_q where q=8380417

Parameters:
  N = 256
  Q = 8380417  
  ψ = 1239911 (primitive 512-th root: ψ^512≡1, ψ^256≡-1)
  ω = 169688 (= ψ² mod Q, primitive 256-th root)

Twiddle pattern matches hardware twiddle_addr mapping
"""

from pathlib import Path

# NTT Parameters (updated for NWC)
N = 256
Q = 8380417
PSI = 1239911
OMEGA = 169688  # ψ² mod Q
WIDTH = 24      # Bit width (log2(Q) ≈ 23, so 24 bits)


def compute_psi_twiddles(n=N, q=Q, psi=PSI):
    """
    Compute ψ-based twiddle factors indexed by twiddle ROM address.

    The hardware uses twiddle_addr = position * 2^(log2(N)-stage-1),
    so we store ψ^addr for addr in [0, N-1].
    """
    return [pow(int(psi), int(addr), q) for addr in range(n)]


def verify_psi_properties(psi=PSI, n=N, q=Q):
    """Verify ψ is primitive 2N-th root of unity"""
    psi_2n = pow(psi, 2*n, q)
    psi_n = pow(psi, n, q)
    omega = (psi * psi) % q
    omega_n = pow(omega, n, q)
    
    print(f"Verifying ψ properties:")
    assert psi_2n == 1, f" ψ^{2*n} = {psi_2n} ≠ 1"
    print(f"  ✓ ψ^{2*n} ≡ 1 (mod {q})")
    
    assert psi_n == q - 1, f"  ψ^{n} = {psi_n} ≠ -1"
    print(f"  ✓ ψ^{n} ≡ -1 (mod {q})")
    
    assert omega == OMEGA, f"  ω = {omega} ≠ {OMEGA}"
    print(f"  ✓ ω = ψ² = {omega}")
    
    assert omega_n == 1, f"  ω^{n} = {omega_n} ≠ 1"
    print(f"  ✓ ω^{n} ≡ 1 (mod {q})")

def generate_systemverilog_rom(twiddles, output_file=None):
    """Generate SystemVerilog ROM with ψ-based twiddles"""
    n_twiddles = len(twiddles)
    addr_width = (n_twiddles - 1).bit_length()
    
    sv_code = f'''`timescale 1ns / 1ps

//==============================================================================
// ψ-Based Twiddle Factor ROM for NWC NTT
//==============================================================================
// Contains precomputed twiddle factors using ψ indexed by address
// 
// Parameters:
//   - N = {N} (NTT size)
//   - Q = {Q} (modulus)
//   - ψ = {PSI} (primitive {2*N}-th root of unity)
//   - ω = {OMEGA} (= ψ², primitive {N}-th root)
//
// Stores ψ^addr for addr in [0, N-1]
// Total entries: {n_twiddles}
//
// Auto-generated by scripts/generate_twiddles.py
//==============================================================================

module twiddle_rom #(
    parameter int N = {N},              // NTT size
    parameter int WIDTH = {WIDTH},       // Bit width (24 bits for Q=8380417)
    parameter int ADDR_WIDTH = {addr_width}   // Address width
) (
    input  logic [ADDR_WIDTH-1:0] addr,    // Read address
    output logic [WIDTH-1:0]      twiddle  // Twiddle factor output
);

    // Twiddle factor lookup table
    always_comb begin
        case (addr)
'''
    
    for i, tw in enumerate(twiddles):
        sv_code += f"            {addr_width}'d{i}: twiddle = {WIDTH}'d{tw};\n"
    
    sv_code += f'''            default: twiddle = {WIDTH}'d0;
        endcase
    end

endmodule
'''
    
    if output_file:
        with open(output_file, 'w') as f:
            f.write(sv_code)
        print(f"✓ Generated SystemVerilog ROM: {output_file}")
    
    return sv_code

def main():
    print("=" * 70)
    print(" ψ-Based NTT Twiddle Factor Generator")
    print("=" * 70)
    print(f"Parameters: N={N}, Q={Q}, ψ={PSI}")
    print()
    
    # Verify ψ properties
    verify_psi_properties(PSI, N, Q)
    print()
    
    # Compute twiddles
    print("Computing ψ-based twiddles for ROM addresses...")
    twiddles = compute_psi_twiddles(N, Q, PSI)
    print(f"✓ Computed {len(twiddles)} twiddle factors")
    print(f"  First 10: {twiddles[:10]}")
    print()
    
    # Determine output directory
    script_dir = Path(__file__).parent
    rtl_dir = script_dir.parent / "rtl"
    rtl_dir.mkdir(exist_ok=True)
    
    # Generate SystemVerilog ROM
    sv_file = rtl_dir / "twiddle_rom.sv"
    generate_systemverilog_rom(twiddles, sv_file)
    
    print()
    print("=" * 70)
    print(" Generation Complete!")
    print("=" * 70)
    print(f"File created: {sv_file}")
    print(f"Total twiddles: {len(twiddles)}")
    print(f"Bit width: {WIDTH}")

if __name__ == "__main__":
    main()
