#!/usr/bin/env python3
"""
Inverse Twiddle Factor Generator for Inverse NWC NTT

Generates inverse twiddle factors: psi^(-k) mod q for k = 0, 1, ..., n-1
where psi^(-1) is the modular inverse of psi.

Outputs:
  - Hex file for BRAM initialization ($readmemh)
  - SystemVerilog ROM (optional, for reference/comparison)

Parameters (default for Dilithium):
  N = 256 (or 4096 for larger NTT)
  Q = 8380417
  psi = 1239911

Usage:
  python generate_inverse_twiddles.py [--n N] [--output-dir DIR]
"""

import argparse
from pathlib import Path


# Default NTT Parameters (Dilithium)
DEFAULT_N = 256
DEFAULT_Q = 8380417
DEFAULT_PSI = 1239911


def mod_inv(a, mod):
    """Compute modular inverse using extended Euclidean algorithm"""

    def extended_gcd(a, b):
        if a == 0:
            return b, 0, 1
        gcd, x1, y1 = extended_gcd(b % a, a)
        x = y1 - (b // a) * x1
        y = x1
        return gcd, x, y

    gcd, x, _ = extended_gcd(a % mod, mod)
    if gcd != 1:
        raise ValueError(f"{a} has no inverse mod {mod}")
    return (x % mod + mod) % mod


def compute_inverse_twiddles(n, q, psi):
    """
    Compute all inverse twiddle factors: psi^(-k) mod q for k = 0, 1, ..., n-1

    Args:
        n: NTT size
        q: Modulus (prime)
        psi: Primitive 2N-th root of unity mod q

    Returns:
        List of n inverse twiddle factors
    """
    psi_inv = mod_inv(psi, q)
    return [pow(psi_inv, k, q) for k in range(n)]


def verify_inverse_properties(psi, n, q):
    """Verify inverse twiddle properties"""
    psi_inv = mod_inv(psi, q)

    print(f"Verifying inverse twiddle properties:")
    print(f"  psi = {psi}")
    print(f"  psi^(-1) = {psi_inv}")

    # Verify psi * psi^(-1) = 1
    product = (psi * psi_inv) % q
    assert product == 1, f"  psi * psi^(-1) = {product} != 1"
    print(f"  psi * psi^(-1) = 1 (mod {q})")

    # Verify psi^(-n) = -1
    psi_neg_n = pow(psi_inv, n, q)
    assert psi_neg_n == q - 1, f"  psi^(-{n}) = {psi_neg_n} != -1"
    print(f"  psi^(-{n}) = -1 (mod {q})")


def generate_hex_file(twiddles, output_file, width=32):
    """
    Generate hex file for $readmemh initialization

    Format: One hex value per line, no address, MSB first
    """
    hex_width = (width + 3) // 4  # Number of hex digits

    with open(output_file, "w") as f:
        for tw in twiddles:
            f.write(f"{tw:0{hex_width}X}\n")

    print(f"Generated hex file: {output_file}")
    print(f"  Entries: {len(twiddles)}")
    print(f"  Width: {width} bits ({hex_width} hex digits)")


def generate_systemverilog_rom(twiddles, output_file, n, q, psi, width=32):
    """Generate SystemVerilog ROM module with case statement (for reference)"""
    psi_inv = mod_inv(psi, q)
    addr_width = (len(twiddles) - 1).bit_length()
    if addr_width == 0:
        addr_width = 1

    sv_code = f"""\
`timescale 1ns / 1ps

//==============================================================================
// Inverse Twiddle Factor ROM for Inverse NTT
//==============================================================================
// Contains precomputed inverse twiddle factors: psi^(-k) mod q
// where psi^(-1) is the inverse of psi mod q
//
// Parameters:
//   - N = {n} (NTT size)
//   - Q = {q} (modulus)
//   - psi = {psi} (primitive {2 * n}-th root of unity)
//   - psi^(-1) = {psi_inv}
//
// Stores psi^(-addr) for addr in [0, N-1]
// Total entries: {len(twiddles)}
//
// Auto-generated by scripts/generate_inverse_twiddles.py
//==============================================================================

module inverse_twiddle_rom #(
    parameter int WIDTH = {width},
    parameter int ADDR_WIDTH = {addr_width}
) (
    input  logic [ADDR_WIDTH-1:0] addr,
    output logic [WIDTH-1:0]      twiddle
);

    // Inverse twiddle factor lookup table
    always_comb begin
        case (addr)
"""

    for i, tw in enumerate(twiddles):
        sv_code += f"            {addr_width}'d{i}: twiddle = {width}'d{tw};\n"

    sv_code += f"""\
            default: twiddle = {width}'d0;
        endcase
    end

endmodule
"""

    with open(output_file, "w") as f:
        f.write(sv_code)

    print(f"Generated SystemVerilog ROM: {output_file}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate inverse NTT twiddle factors for hardware implementation"
    )
    parser.add_argument(
        "--n", type=int, default=DEFAULT_N, help=f"NTT size (default: {DEFAULT_N})"
    )
    parser.add_argument(
        "--q", type=int, default=DEFAULT_Q, help=f"Modulus (default: {DEFAULT_Q})"
    )
    parser.add_argument(
        "--psi",
        type=int,
        default=DEFAULT_PSI,
        help=f"Primitive root (default: {DEFAULT_PSI})",
    )
    parser.add_argument("--width", type=int, default=24, help="Bit width (default: 24)")
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Output directory (default: ../rtl)",
    )
    parser.add_argument(
        "--no-rom", action="store_true", help="Skip generating SystemVerilog ROM"
    )
    args = parser.parse_args()

    # Determine output directory
    script_dir = Path(__file__).parent
    if args.output_dir:
        output_dir = Path(args.output_dir)
    else:
        output_dir = script_dir.parent / "rtl"
    output_dir.mkdir(exist_ok=True)

    print("=" * 70)
    print(" NTT Inverse Twiddle Factor Generator")
    print("=" * 70)
    print(f"Parameters: N={args.n}, Q={args.q}, psi={args.psi}")
    print()

    # Verify inverse properties
    verify_inverse_properties(args.psi, args.n, args.q)
    print()

    # Compute inverse twiddles
    print(f"Computing {args.n} inverse twiddle factors...")
    twiddles = compute_inverse_twiddles(args.n, args.q, args.psi)
    print(f"  First 5: {twiddles[:5]}")
    print(f"  Last 5:  {twiddles[-5:]}")
    print()

    # Generate hex file for BRAM
    hex_file = output_dir / "twiddle_inverse.hex"
    generate_hex_file(twiddles, hex_file, args.width)

    # Generate SystemVerilog ROM (optional)
    if not args.no_rom:
        rom_file = output_dir / "inverse_twiddle_rom.sv"
        generate_systemverilog_rom(
            twiddles, rom_file, args.n, args.q, args.psi, args.width
        )

    print()
    print("=" * 70)
    print(" Generation Complete!")
    print("=" * 70)


if __name__ == "__main__":
    main()
