#!/usr/bin/env python3
"""
Twiddle Factor Generator for NTT

Generates twiddle factors (powers of primitive root of unity) for NTT computation.
For N=256 point NTT over Z_q where q=3329 (Kyber/Dilithium prime).

The primitive 512-th root of unity modulo 3329 is ω = 17.
We need ω^k for k = 0, 1, 2, ..., 255.

Output: SystemVerilog ROM module or memory initialization file.
"""

import sys
from pathlib import Path

# NTT parameters
Q = 3329        # Modulus (Kyber/Dilithium prime)
N = 256         # NTT size
OMEGA = 17      # Primitive 256-th root of unity mod Q (NOT 512-th!)
WIDTH = 32      # Bit width for storage

# Note: For N-point NTT, we actually need a 2N-th root of unity in the standard formulation,
# but for the specific Kyber/Dilithium implementation with N=256 and q=3329,
# ω=17 is used as a primitive 256-th root of unity.
# This works because the NTT is computed differently or twiddles are adjusted.

def compute_twiddle_factors(n=N, q=Q, omega=OMEGA):
    """
    Compute twiddle factors: ω^k mod q for k = 0, 1, ..., n-1
    
    Returns:
        list of n twiddle factors
    """
    twiddles = []
    for k in range(n):
        twiddle = pow(omega, k, q)
        twiddles.append(twiddle)
    return twiddles

def verify_root_of_unity(omega=OMEGA, n=N, q=Q):
    """
    Verify that omega is a primitive n-th root of unity modulo q
    
    For N=256, checks:
        1. ω^256 ≡ 1 (mod q)
        2. ω^128 ≢ 1 (mod q) [primitivity]
    """
    # Check ω^n = 1 mod q
    omega_n = pow(omega, n, q)
    assert omega_n == 1, f"ω^{n} = {omega_n} ≠ 1 (mod {q})"
    
    # Check ω^(n/2) ≠ 1 mod q (primitivity check)
    omega_half = pow(omega, n // 2, q)
    assert omega_half != 1, f"ω^{n//2} = {omega_half} = 1 (mod {q}) - not primitive!"
    
    print(f"✓ ω={omega} is a primitive {n}-th root of unity modulo {q}")
    print(f"  ω^{n} ≡ {omega_n} (mod {q})")
    print(f"  ω^{n//2} ≡ {omega_half} (mod {q})")
    
    # Check if it's also a 2n-th root (nice to have, not required)
    omega_2n = pow(omega, 2*n, q)
    if omega_2n == 1:
        # Check if ω^n = -1
        if omega_n == q - 1:
            print(f"  Bonus: ω is also a primitive {2*n}-th root of unity")
        else:
            print(f"  Note: ω^{2*n} = 1, but ω^{n} ≠ -1, so not a primitive {2*n}-th root")

def generate_systemverilog_rom(twiddles, output_file=None):
    """
    Generate SystemVerilog ROM module with twiddle factors
    """
    n = len(twiddles)
    addr_width = (n - 1).bit_length()
    
    sv_code = f'''`timescale 1ns / 1ps

//==============================================================================
// Twiddle Factor ROM for NTT
//==============================================================================
// Contains precomputed twiddle factors (powers of root of unity)
// 
// Parameters:
//   - N = {n} (NTT size)
//   - Q = {Q} (modulus)
//   - ω = {OMEGA} (primitive {n}-th root of unity)
//
// Stores ω^k mod Q for k = 0, 1, 2, ..., {n-1}
//
// Auto-generated by scripts/generate_twiddles.py
//==============================================================================

module twiddle_rom #(
    parameter int N = {n},              // Number of twiddle factors
    parameter int WIDTH = {WIDTH},      // Bit width
    parameter int ADDR_WIDTH = {addr_width}  // Address width
) (
    input  logic [ADDR_WIDTH-1:0] addr,    // Read address
    output logic [WIDTH-1:0]      twiddle  // Twiddle factor output
);

    // Twiddle factor lookup table
    always_comb begin
        case (addr)
'''
    
    # Generate case statements for each twiddle factor
    for k, tw in enumerate(twiddles):
        sv_code += f"            {addr_width}'d{k}: twiddle = {WIDTH}'d{tw};\n"
    
    sv_code += f'''            default: twiddle = {WIDTH}'d0;
        endcase
    end

endmodule
'''
    
    if output_file:
        with open(output_file, 'w') as f:
            f.write(sv_code)
        print(f"✓ Generated SystemVerilog ROM: {output_file}")
    
    return sv_code

def generate_hex_file(twiddles, output_file=None):
    """
    Generate memory initialization file in hex format
    """
    lines = []
    for tw in twiddles:
        # Format as 32-bit hex (8 hex digits)
        lines.append(f"{tw:08x}\n")
    
    if output_file:
        with open(output_file, 'w') as f:
            f.writelines(lines)
        print(f"✓ Generated hex file: {output_file}")
    
    return ''.join(lines)

def print_statistics(twiddles):
    """Print statistics about twiddle factors"""
    print(f"\nTwiddle Factor Statistics:")
    print(f"  Count: {len(twiddles)}")
    print(f"  Min: {min(twiddles)}")
    print(f"  Max: {max(twiddles)}")
    print(f"  First 10: {twiddles[:10]}")
    print(f"  Last 10: {twiddles[-10:]}")
    
    # Distribution
    histogram = {}
    for tw in twiddles:
        if tw < 1000:
            bucket = "0-999"
        elif tw < 2000:
            bucket = "1000-1999"
        elif tw < 3000:
            bucket = "2000-2999"
        else:
            bucket = "3000-3328"
        histogram[bucket] = histogram.get(bucket, 0) + 1
    
    print(f"\n  Distribution:")
    for bucket, count in sorted(histogram.items()):
        print(f"    {bucket}: {count}")

def main():
    print("=" * 70)
    print(" NTT Twiddle Factor Generator")
    print("=" * 70)
    print(f"Parameters: N={N}, Q={Q}, ω={OMEGA}")
    print()
    
    # Verify root of unity
    verify_root_of_unity(OMEGA, N, Q)
    print()
    
    # Compute twiddle factors
    print(f"Computing {N} twiddle factors...")
    twiddles = compute_twiddle_factors(N, Q, OMEGA)
    print(f"✓ Computed {len(twiddles)} twiddle factors")
    
    # Print statistics
    print_statistics(twiddles)
    print()
    
    # Determine output directory
    script_dir = Path(__file__).parent
    rtl_dir = script_dir.parent / "rtl"
    rtl_dir.mkdir(exist_ok=True)
    
    # Generate SystemVerilog ROM
    sv_file = rtl_dir / "twiddle_rom.sv"
    generate_systemverilog_rom(twiddles, sv_file)
    
    # Generate hex file (optional, for $readmemh if needed)
    hex_file = rtl_dir / "twiddle_factors.hex"
    generate_hex_file(twiddles, hex_file)
    
    print()
    print("=" * 70)
    print(" Generation Complete!")
    print("=" * 70)
    print(f"Files created:")
    print(f"  - {sv_file}")
    print(f"  - {hex_file}")

if __name__ == "__main__":
    main()
