.PHONY: all

FLAGS=-b transparent -t dark

all:
	mmdc -i 3_1_flow.mmd -o 3_1_flow.png ${FLAGS}
	mmdc -i 3_1_flow.mmd -o 3_1_flow.svg ${FLAGS}

	mmdc -i 3_2_structure.mmd -o 3_2_structure.png ${FLAGS}
	mmdc -i 3_2_structure.mmd -o 3_2_structure.svg ${FLAGS}

	mmdc -i 3_3_butterfly.mmd -o 3_3_butterfly.png ${FLAGS}
	mmdc -i 3_3_butterfly.mmd -o 3_3_butterfly.svg ${FLAGS}

	mmdc -i 3_4_rocketchip_integration.mmd -o 3_4_rocketchip_integration.png ${FLAGS}
	mmdc -i 3_4_rocketchip_integration.mmd -o 3_4_rocketchip_integration.svg ${FLAGS}

	mmdc -i 3_6_state_machine.mmd -o 3_6_state_machine.png ${FLAGS}
	mmdc -i 3_6_state_machine.mmd -o 3_6_state_machine.svg ${FLAGS}

	mmdc -i 3_7_ntt_stage.mmd -o 3_7_ntt_stage.png ${FLAGS}
	mmdc -i 3_7_ntt_stage.mmd -o 3_7_ntt_stage.svg ${FLAGS}
